### ISSUE TITLE
It would be great to have checkbox to allow update of Classpath variables

### ISSUE THREAD

**Issue by js402882** [gensth/ProjectLocationUpdater#5]
It would be great to have checkbox to allow update of Classpath variables, e.g. on "Previous Location/New location" screen. If checked it will also replace the prefix in all (maybe selectable :) Classpath variables.

**Comment by gensth** [comment]
That's a great idea. But sorry, I don't want to integrate in the ProjectLocationUpdater. Why that? The plugin was created to be able to update the project location which is stored in a binary file in the eclipse workspace (if not located in a subfolder of the workspace itself). In consequence it was not possible to update the location (in the workspace) when the project was moved to a new location. The plugin solves just this task.
Classpaths are normally stored in your project folder in a file called ".classpath". If you want to change multiple classpaths, I would try to (1) close the eclipse project, (2) edit the ".classpath" file in a text edtior eventually with multiple search/replace and (3) reopen the project again. Furthermore if your project is managed by maven or gradle, these build tools or the according eclipse plugins should manage and eventually update the classpaths of your project.
I hope this addressed your issue/proposal. If not or I didn't understand you correctly feel free to reply.
Best, gensth
